version: "3"

services:
  test-runner:
    container_name: test-runner
    build:
      context: "."
      dockerfile: "Dockerfile.tests"
      args:
        GITHUB_USERNAME: "${GITHUB_USERNAME}"
        GITHUB_TOKEN: "${GITHUB_TOKEN}"
    environment:
      - NEO4J_TEST_URL=bolt://neo4j:7687
    command: [ "go", "test", "-v", "-mod=readonly", "-tags=integration" , "./..." ]
    depends_on:
      - neo4j
  neo4j:
    image: neo4j:4.4-enterprise
    environment:
      - NEO4J_AUTH=none
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
    ports:
      - "7474:7474"
      - "7687:7687"
