apiVersion: v1
description: relations-api Helm chart for Kubernetes
name: relations-api
version: 1.0.1-helm-migration # this entry can be left untouched as it is automatically handled by Jenkins pipeline
