# Values used for the deployed application.
replicaCount: 2
service:
  name: relations-api
env:
  app_port: "8080"

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
          - key: topology.kubernetes.io/zone
            operator: In
            values:
              - us-east-1a


